---
title: "Additional Files"
format:
  html:
    theme: [cosmo, theme.scss]
    toc: true
    toc-depth: 4
    toc-expand: true
---

### What can you find here?

On this page, you can find additional files that are needed or useful in the five sessions. This includes datasets that are used, as well as (rudimentary) solutions to the exercises.

### Datasets
Here you can find the data sets that are used in the sessions.

::: {.callout-important}
## Where to Store Datasets
The R code provided in the sessions assumes that datasets are stored in a folder called '*data*' located within your working directory.
:::

#### Session 1
- [climate_long.Rdata](data/climate_long.Rdata)
- [climate_wide.xlsx](data/climate_wide.xlsx)
- [climate_wide.dta](data/climate_wide.dta)
- [climate.csv](data/climate.csv)

#### Session 2
No datasets used

#### Session 3
- [courses.RData](data/courses.RData)

#### Session 4
- [climate_long.Rdata](data/climate_long.Rdata)
- [climate_wide.Rdata](data/climate_wide.Rdata)
- [climate_wide.xlsx](data/climate_wide.xlsx)
- [climate_wide.dta](data/climate_wide.dta)
- [climate.csv](data/climate.csv)


#### Session 5
- [grades.csv](data/grades.csv)

### Solutions
Here we post solutions to the exercises in the sessions. The files are eventually kept very basic, only having the necessary code. The files, therefore, have very little meaning on their own, but might be useful to consult during the sessions.

#### Session 1
- [Solutions Session 2](solutions/S1.R)

#### Session 2
- [Solutions Session 2](solutions/S2.R)

#### Session 3
- [Solutions Session 3](solutions/S3.R)

#### Session 4
- [Solutions Session 4](solutions/S4.R)

#### Session 5
- [Solutions Session 5](solutions/S5.R)
